classDiagram

    namespace PresentationLayer{
        class

    }

    namespace Business{
        class
    }

    namespace Logic{
        class
    }
    
    namespcae Persitence{
        class
    }
